# Generated by Django 5.2.17 on 2026-09-10 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("slug", models.SlugField(max_length=60, unique=True, verbose_name="slug")),
                ("name_es", models.CharField(max_length=80, verbose_name="nombre (ES)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=80, verbose_name="nombre (EN)"),
                ),
                (
                    "description_es",
                    models.CharField(blank=True, max_length=200, verbose_name="descripción (ES)"),
                ),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=200, verbose_name="descripción (EN)"),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True, verbose_name="slug")),
                ("name_es", models.CharField(max_length=60, verbose_name="nombre (ES)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=60, verbose_name="nombre (EN)"),
                ),
            ],
            options={
                "verbose_name": "etiqueta",
                "verbose_name_plural": "etiquetas",
                "ordering": ("name_es",),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creado"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("published", "Publicado")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="slug")),
                ("title_es", models.CharField(max_length=200, verbose_name="título (ES)")),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=200, verbose_name="título (EN)"),
                ),
                (
                    "excerpt_es",
                    models.TextField(
                        help_text="También se usa como meta description. Máximo 500 caracteres.",
                        max_length=500,
                        verbose_name="extracto (ES)",
                    ),
                ),
                (
                    "excerpt_en",
                    models.TextField(blank=True, max_length=500, verbose_name="extracto (EN)"),
                ),
                (
                    "body_md_es",
                    models.TextField(help_text="Markdown.", verbose_name="contenido (ES)"),
                ),
                ("body_md_en", models.TextField(blank=True, verbose_name="contenido (EN)")),
                ("body_html_es", models.TextField(blank=True, editable=False)),
                ("body_html_en", models.TextField(blank=True, editable=False)),
                ("cover", models.ImageField(blank=True, upload_to="blog/", verbose_name="portada")),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Una fecha futura programa la publicación.",
                        verbose_name="fecha de publicación",
                    ),
                ),
                ("reading_minutes_es", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("reading_minutes_en", models.PositiveSmallIntegerField(default=1, editable=False)),
                (
                    "views",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="lecturas"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="blog.category",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.tag", verbose_name="etiquetas"
                    ),
                ),
            ],
            options={
                "verbose_name": "publicación",
                "verbose_name_plural": "publicaciones",
                "ordering": ("-published_at",),
                "indexes": [
                    models.Index(fields=["status", "-published_at"], name="post_listing_idx")
                ],
            },
        ),
    ]
