# Generated by Django 5.2.17 on 2026-09-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creado"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                ("full_name", models.CharField(max_length=120, verbose_name="nombre completo")),
                ("role_es", models.CharField(max_length=160, verbose_name="rol (ES)")),
                ("role_en", models.CharField(blank=True, max_length=160, verbose_name="rol (EN)")),
                (
                    "headline_es",
                    models.CharField(
                        help_text="Frase principal del hero. Corta y concreta.",
                        max_length=255,
                        verbose_name="titular (ES)",
                    ),
                ),
                (
                    "headline_en",
                    models.CharField(blank=True, max_length=255, verbose_name="titular (EN)"),
                ),
                ("bio_es", models.TextField(help_text="Markdown.", verbose_name="biografía (ES)")),
                ("bio_en", models.TextField(blank=True, verbose_name="biografía (EN)")),
                ("bio_html_es", models.TextField(blank=True, editable=False)),
                ("bio_html_en", models.TextField(blank=True, editable=False)),
                ("email", models.EmailField(max_length=254, verbose_name="correo")),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="teléfono")),
                ("location_es", models.CharField(max_length=120, verbose_name="ubicación (ES)")),
                (
                    "location_en",
                    models.CharField(blank=True, max_length=120, verbose_name="ubicación (EN)"),
                ),
                (
                    "availability_es",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="disponibilidad (ES)"
                    ),
                ),
                (
                    "availability_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="disponibilidad (EN)"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="profile/", verbose_name="foto"),
                ),
                (
                    "cv_es",
                    models.FileField(blank=True, upload_to="cv/", verbose_name="CV en español"),
                ),
                (
                    "cv_en",
                    models.FileField(blank=True, upload_to="cv/", verbose_name="CV en inglés"),
                ),
            ],
            options={
                "verbose_name": "perfil",
                "verbose_name_plural": "perfil",
            },
        ),
        migrations.CreateModel(
            name="ExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("role_es", models.CharField(max_length=160, verbose_name="puesto (ES)")),
                (
                    "role_en",
                    models.CharField(blank=True, max_length=160, verbose_name="puesto (EN)"),
                ),
                ("organization", models.CharField(max_length=160, verbose_name="organización")),
                ("start_date", models.DateField(verbose_name="desde")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Vacío = actual.", null=True, verbose_name="hasta"
                    ),
                ),
                ("description_es", models.TextField(blank=True, verbose_name="descripción (ES)")),
                ("description_en", models.TextField(blank=True, verbose_name="descripción (EN)")),
                (
                    "highlights_es",
                    models.TextField(
                        blank=True, help_text="Un aporte por línea.", verbose_name="aportes (ES)"
                    ),
                ),
                ("highlights_en", models.TextField(blank=True, verbose_name="aportes (EN)")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="site_content.profile",
                        verbose_name="perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "experiencia",
                "verbose_name_plural": "experiencia",
                "ordering": ("-start_date", "order"),
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("name_es", models.CharField(max_length=80, verbose_name="nombre (ES)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=80, verbose_name="nombre (EN)"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_groups",
                        to="site_content.profile",
                        verbose_name="perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo de habilidades",
                "verbose_name_plural": "grupos de habilidades",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nombre")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 · Básico"),
                            (2, "2"),
                            (3, "3 · Sólido"),
                            (4, "4"),
                            (5, "5 · Avanzado"),
                        ],
                        default=3,
                        verbose_name="nivel",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Las destacadas aparecen en el resumen del hero.",
                        verbose_name="destacada",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="site_content.skillgroup",
                        verbose_name="grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "habilidad",
                "verbose_name_plural": "habilidades",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="GitHub, LinkedIn…", max_length=40, verbose_name="nombre"
                    ),
                ),
                ("url", models.URLField(verbose_name="enlace")),
                (
                    "icon",
                    models.CharField(
                        help_text="Identificador del icono en el frontend: github, linkedin, mail…",
                        max_length=40,
                        verbose_name="icono",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="site_content.profile",
                        verbose_name="perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "enlace social",
                "verbose_name_plural": "enlaces sociales",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
