# Generated by Django 5.2.17 on 2026-09-10 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("slug", models.SlugField(max_length=40, unique=True, verbose_name="slug")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quiz", "Cuestionario (se corrige en el servidor)"),
                            ("arcade", "Arcade (puntuación enviada por el cliente)"),
                        ],
                        default="arcade",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("name_es", models.CharField(max_length=80, verbose_name="nombre (ES)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=80, verbose_name="nombre (EN)"),
                ),
                (
                    "description_es",
                    models.CharField(max_length=255, verbose_name="descripción (ES)"),
                ),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=255, verbose_name="descripción (EN)"),
                ),
                ("icon", models.CharField(blank=True, max_length=40, verbose_name="icono")),
                (
                    "enabled",
                    models.BooleanField(db_index=True, default=True, verbose_name="activo"),
                ),
                (
                    "max_plausible_score",
                    models.PositiveIntegerField(
                        default=10000,
                        help_text="Cualquier envío por encima de este valor se rechaza.",
                        verbose_name="puntuación máxima creíble",
                    ),
                ),
                (
                    "min_duration_ms",
                    models.PositiveIntegerField(
                        default=3000,
                        help_text="Una partida más corta que esto no es humana.",
                        verbose_name="duración mínima (ms)",
                    ),
                ),
            ],
            options={
                "verbose_name": "juego",
                "verbose_name_plural": "juegos",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("text_es", models.TextField(verbose_name="pregunta (ES)")),
                ("text_en", models.TextField(blank=True, verbose_name="pregunta (EN)")),
                (
                    "explanation_es",
                    models.TextField(
                        blank=True,
                        help_text="Se muestra después de responder. Es lo que convierte el juego en algo útil.",
                        verbose_name="explicación (ES)",
                    ),
                ),
                ("explanation_en", models.TextField(blank=True, verbose_name="explicación (EN)")),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Fácil · 10 pts"),
                            (2, "Media · 20 pts"),
                            (3, "Difícil · 30 pts"),
                        ],
                        default=1,
                        verbose_name="dificultad",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="games.game",
                        verbose_name="juego",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregunta",
                "verbose_name_plural": "preguntas",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("text_es", models.CharField(max_length=255, verbose_name="opción (ES)")),
                (
                    "text_en",
                    models.CharField(blank=True, max_length=255, verbose_name="opción (EN)"),
                ),
                ("is_correct", models.BooleanField(default=False, verbose_name="es correcta")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="games.quizquestion",
                        verbose_name="pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "opción",
                "verbose_name_plural": "opciones",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creado"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                ("nickname", models.CharField(max_length=16, verbose_name="apodo")),
                (
                    "score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="puntuación",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="duración (ms)"),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="detalle")),
                ("ip_hash", models.CharField(db_index=True, editable=False, max_length=64)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="games.game",
                        verbose_name="juego",
                    ),
                ),
            ],
            options={
                "verbose_name": "puntuación",
                "verbose_name_plural": "puntuaciones",
                "ordering": ("-score", "created_at"),
                "indexes": [
                    models.Index(fields=["game", "-score", "created_at"], name="score_ranking_idx")
                ],
            },
        ),
    ]
