# Generated by Django 5.2.17 on 2026-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="repo_url",
            field=models.URLField(
                blank=True,
                help_text="Si el juego tiene su propio repositorio, se enlaza junto a la descripción. Vale para los que se desarrollaron aparte y luego se integraron aquí.",
                verbose_name="repositorio",
            ),
        ),
    ]
