# Generated by Django 5.2.17 on 2026-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="La que se ve en la tarjeta del listado de juegos.",
                upload_to="games/",
                verbose_name="portada",
            ),
        ),
    ]
