# Generated by Django 5.2.17 on 2026-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creado"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="correo")),
                ("subject", models.CharField(max_length=200, verbose_name="asunto")),
                ("message", models.TextField(max_length=5000, verbose_name="mensaje")),
                ("locale", models.CharField(default="es", max_length=5, verbose_name="idioma")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("read", "Leído"),
                            ("replied", "Respondido"),
                            ("spam", "Spam"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text="False significa que el mensaje se guardó pero el envío SMTP falló.",
                        verbose_name="notificado por correo",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, editable=False, max_length=64)),
                ("user_agent", models.CharField(blank=True, editable=False, max_length=300)),
            ],
            options={
                "verbose_name": "mensaje",
                "verbose_name_plural": "mensajes",
                "ordering": ("-created_at",),
            },
        ),
    ]
