# Generated by Django 5.2.17 on 2026-09-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="delivered",
            field=models.BooleanField(
                default=False,
                help_text="Sin marcar: el mensaje se guardó, pero el aviso no se pudo entregar.",
                verbose_name="avisado",
            ),
        ),
    ]
