# Generated by Django 5.2.17 on 2026-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cpu_percent", models.FloatField(verbose_name="CPU (%)")),
                ("mem_used_mb", models.PositiveIntegerField(verbose_name="RAM usada (MB)")),
                ("mem_total_mb", models.PositiveIntegerField(verbose_name="RAM total (MB)")),
                ("disk_used_gb", models.FloatField(verbose_name="disco usado (GB)")),
                ("disk_total_gb", models.FloatField(verbose_name="disco total (GB)")),
                ("load_1m", models.FloatField(default=0.0, verbose_name="carga 1 min")),
                (
                    "uptime_seconds",
                    models.PositiveBigIntegerField(default=0, verbose_name="uptime (s)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "muestra de métricas",
                "verbose_name_plural": "muestras de métricas",
                "ordering": ("-created_at",),
            },
        ),
    ]
