# Generated by Django 5.2.17 on 2026-09-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="creado"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("published", "Publicado")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="slug")),
                ("title_es", models.CharField(max_length=160, verbose_name="título (ES)")),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=160, verbose_name="título (EN)"),
                ),
                (
                    "tagline_es",
                    models.CharField(
                        help_text="Una línea para la tarjeta.",
                        max_length=255,
                        verbose_name="frase (ES)",
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(blank=True, max_length=255, verbose_name="frase (EN)"),
                ),
                (
                    "summary_es",
                    models.TextField(help_text="Dos o tres frases.", verbose_name="resumen (ES)"),
                ),
                ("summary_en", models.TextField(blank=True, verbose_name="resumen (EN)")),
                (
                    "body_md_es",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="caso de estudio (ES)"
                    ),
                ),
                ("body_md_en", models.TextField(blank=True, verbose_name="caso de estudio (EN)")),
                ("body_html_es", models.TextField(blank=True, editable=False)),
                ("body_html_en", models.TextField(blank=True, editable=False)),
                ("role_es", models.CharField(blank=True, max_length=160, verbose_name="rol (ES)")),
                ("role_en", models.CharField(blank=True, max_length=160, verbose_name="rol (EN)")),
                (
                    "cover",
                    models.ImageField(blank=True, upload_to="projects/", verbose_name="portada"),
                ),
                ("year", models.PositiveIntegerField(db_index=True, verbose_name="año")),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece en la página de inicio.",
                        verbose_name="destacado",
                    ),
                ),
                ("repo_url", models.URLField(blank=True, verbose_name="repositorio")),
                ("live_url", models.URLField(blank=True, verbose_name="sitio en vivo")),
                (
                    "store_url",
                    models.URLField(
                        blank=True, help_text="Google Play, App Store…", verbose_name="tienda"
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="demostración en video")),
            ],
            options={
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
                "ordering": ("order", "-year"),
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("name", models.CharField(max_length=60, unique=True, verbose_name="nombre")),
                ("slug", models.SlugField(max_length=60, unique=True, verbose_name="slug")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("devops", "DevOps"),
                            ("database", "Bases de datos"),
                            ("design", "Diseño"),
                        ],
                        db_index=True,
                        default="backend",
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hexadecimal, por ejemplo #7F52FF para Kotlin.",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=60, verbose_name="icono")),
            ],
            options={
                "verbose_name": "tecnología",
                "verbose_name_plural": "tecnologías",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/", verbose_name="imagen")),
                (
                    "caption_es",
                    models.CharField(blank=True, max_length=200, verbose_name="pie (ES)"),
                ),
                (
                    "caption_en",
                    models.CharField(blank=True, max_length=200, verbose_name="pie (EN)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                        verbose_name="proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen del proyecto",
                "verbose_name_plural": "galería",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="orden"),
                ),
                ("label_es", models.CharField(max_length=80, verbose_name="etiqueta (ES)")),
                (
                    "label_en",
                    models.CharField(blank=True, max_length=80, verbose_name="etiqueta (EN)"),
                ),
                ("value", models.CharField(max_length=60, verbose_name="valor")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="projects.project",
                        verbose_name="proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "métrica del proyecto",
                "verbose_name_plural": "métricas",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.technology",
                verbose_name="tecnologías",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status", "featured", "-year"], name="project_listing_idx"),
        ),
    ]
